### PR TITLE
Issues/9

### PR DESCRIPTION
**Pull request by mrohban**
added the numerically stable parallel cor function to report the feature correlations

### CODE REVIEW

**Comment by shntnu** [comment]
Great to see this implementation!

Most of the commits I have made are structural changes using http://r-pkgs.had.co.nz/src.html as a guide. A lot of the changes are auto-generated. 

Can you make a few more changes?
- document the params in `custom_covar.cpp`
- `combine_covs` is a little confusing - consider renaming
- similarly, `custom_` is ambiguous. Instead, `robust_` or `efficient_` or `stable_`?
- add any other tests you think are useful 

Note: After you make changes in the cpp files, do Cmd + Shift + D (document) and Cmd + Shift + B (build) for all the auto-generated stuff to happen.

**Comment by mrohban** [comment]
I have updated it based on the comments, I guess there is a problem regarding `devtools::document` which made Travis fail.

**Comment by mrohban** [comment]
OK, fixed it now.

**Comment by shntnu** [comment]
@mrohban I refactored more. 
Some notes
- For the C++ code – I renamed stuff based on my understanding of the code. Feel free to change that if you don't agree with the names.
- Use `tidyr` instead of `reshape2`
- I'm using http://r-pkgs.had.co.nz/r.html as a style guide - worth reading that at some point

If you agree with all the changes, please go ahead and close, merge, delete branch and resolve #9

**Pull request merged**
